version: '3.3'
services:

  app:
    build: .
    restart: unless-stopped
    ports:
      - '$APP_PORT_EXT:3000'
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_USER: $MONGO_APP_USER
      MONGO_PASSWORD: $MONGO_APP_PWD
      MONGO_DATABASE: $MONGO_DB_NAME

  db:
    image: mongo:5.0.6
    restart: unless-stopped
    ports: 
      - '$MONGO_PORT_EXT:27017'
    volumes:
      - './mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh'
      - 'srvexo-data-db:/data/db'
    environment:
      MONGO_INITDB_USER: $MONGO_APP_USER
      MONGO_INITDB_PASSWORD: $MONGO_APP_PWD
      MONGO_INITDB_DATABASE: $MONGO_DB_NAME

volumes:
  srvexo-data-db:
